apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deployment
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: haidyh/spring-boot-app:latest
          ports:
            - containerPort: 8080